### PR TITLE
Uncomment all lines in entities

### PR DESCRIPTION
**Pull request by chazzybearr**
Modify corresponding tests

### CODE REVIEW

**Comment by chazzybearr** [comment]
All the previously made comments made in our entities have been uncommented and tests have been modified to line up with these changes

**Comment by chazzybearr** [comment]
database.txt was necessary for database tests since you can't push a folder, but you have to have at least one file inside said folder to it show up on Github. (I was getting an InvalidClassException since Vishnu and I ran the tests and different machines and thus generated different serialVersionUID's from serialization.)

**Review by Dawei-He2002 — APPROVED** [review]
Everything looks good. Nice to see that the GetChatRoom method is now implemented.

**Review by paridhi26 — APPROVED** [review]

**Comment by paridhi26** [comment]
Why does this commit include TimerInputData? It is creating the conflict. Is it possible to just delete it? That file is the old one anyway, and I commit the new one soon.

**Review by nitvishn — APPROVED** [review]
looks good.

**Pull request closed without merging**
