### PR TITLE
1-feature-1-task-list

### PR DESCRIPTION
**Pull request by chazzybearr**
Added a Tag entity class with methods and attributes that depend on other classes not implemented yet commented out

### CODE REVIEW

**Review by Dawei-He2002 — DISMISSED** [review]
Now we can finally test the files without the Tag class being missing.

**Review by Dawei-He2002 — APPROVED** [review]
I think everything's good here.

**Review by nitvishn — APPROVED** [review]
Everything looks good!

**Comment by paridhi26** [comment]
Looks good!

**Review by kldtntg — APPROVED** [review]

**Pull request merged**
